name: Build Self-Contained EXE

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore dependencies
        run: dotnet restore src/X6ProUnLocker.sln
      - name: Build
        # 👇 исправлен путь к .csproj (теперь прямо в src)
        run: dotnet publish src/X6ProUnLocker.csproj -c Release -o publish -r win-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: X6ProUnLocker
          path: publish/X6ProUnLocker.exe